### PR TITLE
Add SPAT

### PR DESCRIPTION
**Pull request by treiher**

### CODE REVIEW

**Review by jklmnn — COMMENTED** [review]
Do we want to name it spat-2020? Because when we're going to upgrade this container to GNAT CE 2021 anything that uses spat and has not yet been updated to the newer GNAT will probably break.

**Comment by treiher** [comment]
I intended this image solely for executing SPAT and nothing else. But of course the current design does not prevent it from being misused. Do you think we have to enforce that? I don't think it would make sense to create a separate SPAT image for each GNAT version. That would be just more images to administrate. At the current state I see no issue to run SPAT (based on CE 2020) in a project where CE 2019 or CE 2021 is actually used.

**Comment by jklmnn** [comment]
But when you run SPAT doesn't it use gnatprove? So it would still fail if it used the wrong version. If it doesn't use gnatprove it might make sense to not depend on the GNAT container to make the image smaller.

**Comment by treiher** [comment]
SPAT is not a wrapper like sparkprof. It analyzes the `.spark` files created by `gnatprove`.

I changed the image so that no GNAT is contained in the final image.

**Review by jklmnn — APPROVED** [review]

**Review by senier — APPROVED** [review]

**Pull request merged**
